#!  /bin/bash
#RM_SELINUX_RULE=enable
#
#  PRNL=dcp1600lpr-3.0.1-1.i386.rpm
#  PRNC=dcp1600cupswrapper-3.0.1-1.i386.rpm
#  PRNP=
#  SCAN=brscan4-0.4.11-1.x86_64.rpm
#  SKEY=brscan-skey-0.3.1-2.x86_64.rpm
#
if [ "$RM_SELINUX_RULE" = "enable" ];then
  echo semanage fcontext -d -t bin_t '/opt/brother'
  semanage fcontext -d -t bin_t '/opt/brother'
  echo restorecon -R /opt/brother
  restorecon -R /opt/brother
  echo semanage fcontext -d -t cupsd_rw_etc_t '/etc/opt/brother'
  semanage fcontext -d -t cupsd_rw_etc_t '/etc/opt/brother'
  echo restorecon -R /etc/opt/brother
  restorecon -R /etc/opt/brother
  echo semanage fcontext -d -t cupsd_rw_etc_t '/opt/brother/Printers/(.*/)?inf(/.*)?'
  semanage fcontext -d -t cupsd_rw_etc_t '/opt/brother/Printers/(.*/)?inf(/.*)?'
  echo restorecon -R /opt/brother/Printers
  restorecon -R /opt/brother/Printers
  echo semanage fcontext -d -t cupsd_rw_etc_t '/etc/opt/brother/Printers/(.*/)?inf(/.*)?'
  semanage fcontext -d -t cupsd_rw_etc_t '/etc/opt/brother/Printers/(.*/)?inf(/.*)?'
  echo restorecon -R /etc/opt/brother/Printers
  restorecon -R /etc/opt/brother/Printers
  echo semanage fcontext -d -t bin_t '/opt/brother/Printers/(.*/)?lpd(/.*)?'
  semanage fcontext -d -t bin_t '/opt/brother/Printers/(.*/)?lpd(/.*)?'
  echo restorecon -R /opt/brother/Printers
  restorecon -R /opt/brother/Printers
  echo semanage fcontext -d -t bin_t '/opt/brother/Printers/(.*/)?cupswrapper(/.*)?'
  semanage fcontext -d -t bin_t '/opt/brother/Printers/(.*/)?cupswrapper(/.*)?'
  echo restorecon -R /opt/brother/Printers
  restorecon -R /opt/brother/Printers
  echo setsebool -P cups_execmem 0
  setsebool -P cups_execmem 0
fi
if ! [ -f /etc/init.d/cupsys ];then
 DUMMYCUPSYS=1
 ln -s /bin/true  /etc/init.d/cupsys
fi
if ! [ -f /etc/init.d/cups ];then
 DUMMYCUPS=1
 ln -s /bin/true  /etc/init.d/cups
fi
if ! [ -f /etc/init.d/lpd ];then
 DUMMYLPD=1
 ln -s /bin/true  /etc/init.d/lpd
fi
if ! [ -f /etc/init.d/lprng ];then
 DUMMYLPRNG=1
 ln -s /bin/true  /etc/init.d/lprng
fi

rpm -e    dcp1600cupswrapper

rpm -e    dcp1600lpr
if [ "$DUMMYCUPS" = 1 ];then
  lsc=$(ls -al /etc/init.d/cups  2> /dev/null| grep ^l)
  if [ "$lsc" != "" ];then
    rm -f /etc/init.d/cups
  fi
fi

if [ "$DUMMYCUPSYS" = 1 ];then
  lsc=$(ls -al /etc/init.d/cupsys  2> /dev/null| grep ^l)
  if [ "$lsc" != "" ];then
    rm -f /etc/init.d/cupsys
  fi
fi

if [ "$DUMMYLPD" = 1 ];then
  lsc=$(ls -al /etc/init.d/lpd  2> /dev/null | grep ^l)
  if [ "$lsc" != "" ];then
    rm -f /etc/init.d/lpd
  fi
fi

if [ "$DUMMYLPRNG" = 1 ];then
  lsc=$(ls -al /etc/init.d/lprng | grep ^l)
  if [ "$lsc" != "" ];then
    rm -f /etc/init.d/lprng
  fi
fi


